export { default as Appointment } from './appointment/Appointment'
export { default as Treatment } from './treatment/Treatment'
export { default as Receipt } from './Receipt'
export { default as Patients } from './patient/Patients'
export { default as NotFound } from './404/NotFound'
export { default as WaitingList } from './waitingList/WaitingList'
export { default as MedicalRegistration } from './medicalRegistration/MedicalRegistration'
export { default as DentistWaitingList } from './waitingList/DentistWaitingList'
export { default as Login } from './login/Login'
export { default as DentalCareRecord } from './treatment/dentalRecord/DentalCareRecord'
export { default as Bill } from './bill'
export { default as TestAdmin } from './admin/TestAdmin'
export { default as OwnerTest } from './owner/OwnerTest'
export { default as HistoryRecord } from './treatment/recordHistory'

export { default as AllBill } from './patient/hoadon'
export { default as TestDemo } from './demo/TestDemo'