export { default as Appointment } from './appointment/Appointment'
export { default as Treatment } from './Treatment'
export { default as Receipt } from './Receipt'
export { default as Patients } from './Patients'
export { default as NotFound } from './404/NotFound'
export { default as WaitingList } from './waitingList/WaitingList'
export { default as MedicalRegistration } from './medicalRegistration/MedicalRegistration'
export { default as StaffWaitingList } from './waitingList/StaffWaitingList'